language: python
sudo: false
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.6"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
      dist: xenial
      sudo: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
  - pip install -r requirements-$PLONE_VERSION.txt
  - ln -sf plone-$PLONE_VERSION.cfg buildout.cfg
install:
  - buildout -N annotate
  - buildout -N
script:
  - bin/test yafowil.plone
